<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="4" total="13" passed="0" failed="9" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2018-11-12T19:39:03Z" name="All login tests" finished-at="2018-11-12T19:42:38Z" duration-ms="214816">
    <groups>
    </groups>
    <test started-at="2018-11-12T19:39:03Z" name="positive" finished-at="2018-11-12T19:39:53Z" duration-ms="50333">
      <class name="test.LoginTest3">
        <test-method is-config="true" signature="beforeMethod()[pri:0, instance:test.LoginTest3@4c402120]" started-at="2018-11-12T19:39:03Z" name="beforeMethod" finished-at="2018-11-12T19:39:27Z" duration-ms="23949" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method signature="successfullLoginTest(java.lang.String, java.lang.String)[pri:0, instance:test.LoginTest3@4c402120]" started-at="2018-11-12T19:39:27Z" name="successfullLoginTest" data-provider="validationMessagesCombinations" finished-at="2018-11-12T19:39:27Z" duration-ms="34" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[test199514@gmail.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[!Test6141026]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Login page is not loaded. expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Login page is not loaded. expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at test.LoginTest3.successfullLoginTest(LoginTest3.java:63)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:379)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:340)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:125)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:413)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- successfullLoginTest -->
        <test-method is-config="true" signature="afterMethod()[pri:0, instance:test.LoginTest3@4c402120]" started-at="2018-11-12T19:39:27Z" name="afterMethod" finished-at="2018-11-12T19:39:34Z" duration-ms="6765" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method is-config="true" signature="beforeMethod()[pri:0, instance:test.LoginTest3@4c402120]" started-at="2018-11-12T19:39:34Z" name="beforeMethod" finished-at="2018-11-12T19:39:48Z" duration-ms="13838" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method signature="successfullLoginTest(java.lang.String, java.lang.String)[pri:0, instance:test.LoginTest3@4c402120]" started-at="2018-11-12T19:39:48Z" name="successfullLoginTest" data-provider="validationMessagesCombinations" finished-at="2018-11-12T19:39:48Z" duration-ms="52" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[ test199514@gmail.com ]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[!Test6141026]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Login page is not loaded. expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Login page is not loaded. expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at test.LoginTest3.successfullLoginTest(LoginTest3.java:63)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:379)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:340)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:125)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:413)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- successfullLoginTest -->
        <test-method is-config="true" signature="afterMethod()[pri:0, instance:test.LoginTest3@4c402120]" started-at="2018-11-12T19:39:48Z" name="afterMethod" finished-at="2018-11-12T19:39:53Z" duration-ms="5548" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
      </class> <!-- test.LoginTest3 -->
    </test> <!-- positive -->
    <test started-at="2018-11-12T19:39:54Z" name="negative" finished-at="2018-11-12T19:42:38Z" duration-ms="164008">
      <class name="test.LoginTest3">
        <test-method is-config="true" signature="beforeMethod()[pri:0, instance:test.LoginTest3@1fa121e2]" started-at="2018-11-12T19:39:54Z" name="beforeMethod" finished-at="2018-11-12T19:41:01Z" duration-ms="67449" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method signature="validationMessagesInvalidEmailPasswordTest(java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:test.LoginTest3@1fa121e2]" started-at="2018-11-12T19:41:01Z" name="validationMessagesInvalidEmailPasswordTest" data-provider="negativeValidDataProviderLoginSubmitPage" finished-at="2018-11-12T19:41:01Z" duration-ms="19" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[test199514@gmail.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[g3434kd4]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[РЈРєР°Р¶РёС‚Рµ РґРµР№СЃС‚РІРёС‚РµР»СЊРЅС‹Р№ Р°РґСЂРµСЃ СЌР». РїРѕС‡С‚С‹.]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[Р­С‚Рѕ РЅРµРІРµСЂРЅС‹Р№ РїР°СЂРѕР»СЊ. РџРѕРІС‚РѕСЂРёС‚Рµ РїРѕРїС‹С‚РєСѓ РёР»Рё РёР·РјРµРЅРёС‚Рµ РїР°СЂРѕР»СЊ.]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Login page is not loaded. expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Login page is not loaded. expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at test.LoginTest3.validationMessagesInvalidEmailPasswordTest(LoginTest3.java:72)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:379)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:340)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:125)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:413)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validationMessagesInvalidEmailPasswordTest -->
        <test-method is-config="true" signature="afterMethod()[pri:0, instance:test.LoginTest3@1fa121e2]" started-at="2018-11-12T19:41:01Z" name="afterMethod" finished-at="2018-11-12T19:41:04Z" duration-ms="2724" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method is-config="true" signature="beforeMethod()[pri:0, instance:test.LoginTest3@1fa121e2]" started-at="2018-11-12T19:41:04Z" name="beforeMethod" finished-at="2018-11-12T19:41:27Z" duration-ms="23070" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method signature="validationMessagesInvalidEmailPasswordTest(java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:test.LoginTest3@1fa121e2]" started-at="2018-11-12T19:41:27Z" name="validationMessagesInvalidEmailPasswordTest" data-provider="negativeValidDataProviderLoginSubmitPage" finished-at="2018-11-12T19:41:27Z" duration-ms="19" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[a@g.c]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[!Test6141026]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[РЈРєР°Р¶РёС‚Рµ РґРµР№СЃС‚РІРёС‚РµР»СЊРЅС‹Р№ Р°РґСЂРµСЃ СЌР». РїРѕС‡С‚С‹.]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[Р­С‚Рѕ РЅРµРІРµСЂРЅС‹Р№ РїР°СЂРѕР»СЊ. РџРѕРІС‚РѕСЂРёС‚Рµ РїРѕРїС‹С‚РєСѓ РёР»Рё РёР·РјРµРЅРёС‚Рµ РїР°СЂРѕР»СЊ.]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Login page is not loaded. expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Login page is not loaded. expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at test.LoginTest3.validationMessagesInvalidEmailPasswordTest(LoginTest3.java:72)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:379)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:340)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:125)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:413)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validationMessagesInvalidEmailPasswordTest -->
        <test-method is-config="true" signature="afterMethod()[pri:0, instance:test.LoginTest3@1fa121e2]" started-at="2018-11-12T19:41:27Z" name="afterMethod" finished-at="2018-11-12T19:41:29Z" duration-ms="2046" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method is-config="true" signature="beforeMethod()[pri:0, instance:test.LoginTest3@1fa121e2]" started-at="2018-11-12T19:41:29Z" name="beforeMethod" finished-at="2018-11-12T19:41:39Z" duration-ms="9784" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method signature="validationMessagesInvalidEmailPasswordTest(java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:test.LoginTest3@1fa121e2]" started-at="2018-11-12T19:41:39Z" name="validationMessagesInvalidEmailPasswordTest" data-provider="negativeValidDataProviderLoginSubmitPage" finished-at="2018-11-12T19:41:39Z" duration-ms="17" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[ladfhlalf]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[!Test6141026]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[РЈРєР°Р¶РёС‚Рµ РґРµР№СЃС‚РІРёС‚РµР»СЊРЅС‹Р№ Р°РґСЂРµСЃ СЌР». РїРѕС‡С‚С‹.]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[Р­С‚Рѕ РЅРµРІРµСЂРЅС‹Р№ РїР°СЂРѕР»СЊ. РџРѕРІС‚РѕСЂРёС‚Рµ РїРѕРїС‹С‚РєСѓ РёР»Рё РёР·РјРµРЅРёС‚Рµ РїР°СЂРѕР»СЊ.]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Login page is not loaded. expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Login page is not loaded. expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at test.LoginTest3.validationMessagesInvalidEmailPasswordTest(LoginTest3.java:72)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:379)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:340)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:125)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:413)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validationMessagesInvalidEmailPasswordTest -->
        <test-method is-config="true" signature="afterMethod()[pri:0, instance:test.LoginTest3@1fa121e2]" started-at="2018-11-12T19:41:39Z" name="afterMethod" finished-at="2018-11-12T19:41:41Z" duration-ms="2258" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method is-config="true" signature="beforeMethod()[pri:0, instance:test.LoginTest3@1fa121e2]" started-at="2018-11-12T19:41:41Z" name="beforeMethod" finished-at="2018-11-12T19:41:53Z" duration-ms="11833" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method signature="validationMessagesInvalidEmailPasswordTest(java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:test.LoginTest3@1fa121e2]" started-at="2018-11-12T19:41:53Z" name="validationMessagesInvalidEmailPasswordTest" data-provider="negativeValidDataProviderLoginSubmitPage" finished-at="2018-11-12T19:41:53Z" duration-ms="18" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[ghtyhgvbnhghtyhgvbnhghtyhgvbnhghtyhgvbnhghtyhgvbnhghtyhgvbnhghtyhgvbnhghtyhgvbnhghtyhgvbnhghtyhgvbnhghtyhgvb]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[!Test6141026]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[РЈРєР°Р¶РёС‚Рµ РґРµР№СЃС‚РІРёС‚РµР»СЊРЅС‹Р№ Р°РґСЂРµСЃ СЌР». РїРѕС‡С‚С‹.]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[Р­С‚Рѕ РЅРµРІРµСЂРЅС‹Р№ РїР°СЂРѕР»СЊ. РџРѕРІС‚РѕСЂРёС‚Рµ РїРѕРїС‹С‚РєСѓ РёР»Рё РёР·РјРµРЅРёС‚Рµ РїР°СЂРѕР»СЊ.]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Login page is not loaded. expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Login page is not loaded. expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at test.LoginTest3.validationMessagesInvalidEmailPasswordTest(LoginTest3.java:72)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:379)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:340)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:125)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:413)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validationMessagesInvalidEmailPasswordTest -->
        <test-method is-config="true" signature="afterMethod()[pri:0, instance:test.LoginTest3@1fa121e2]" started-at="2018-11-12T19:41:53Z" name="afterMethod" finished-at="2018-11-12T19:41:55Z" duration-ms="2505" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method is-config="true" signature="beforeMethod()[pri:0, instance:test.LoginTest3@1fa121e2]" started-at="2018-11-12T19:41:55Z" name="beforeMethod" finished-at="2018-11-12T19:42:06Z" duration-ms="10941" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method signature="validationMessagesInvalidEmailPasswordTest(java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:test.LoginTest3@1fa121e2]" started-at="2018-11-12T19:42:06Z" name="validationMessagesInvalidEmailPasswordTest" data-provider="negativeValidDataProviderLoginSubmitPage" finished-at="2018-11-12T19:42:06Z" duration-ms="15" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[asdwqasdfeasdwqasdfeasdwqasdfeasdwqasdfeasdwqasdfeasdwqasdfeasdwqasdfeasdwqasdfeasdwqasdfeasdwqasdfeasdwqasdfeasdwqasdfeasdwqasdfeasdwqasdfe]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[!Test6141026]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[РЈРєР°Р¶РёС‚Рµ РґРµР№СЃС‚РІРёС‚РµР»СЊРЅС‹Р№ Р°РґСЂРµСЃ СЌР». РїРѕС‡С‚С‹.]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[Р­С‚Рѕ РЅРµРІРµСЂРЅС‹Р№ РїР°СЂРѕР»СЊ. РџРѕРІС‚РѕСЂРёС‚Рµ РїРѕРїС‹С‚РєСѓ РёР»Рё РёР·РјРµРЅРёС‚Рµ РїР°СЂРѕР»СЊ.]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Login page is not loaded. expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Login page is not loaded. expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at test.LoginTest3.validationMessagesInvalidEmailPasswordTest(LoginTest3.java:72)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:379)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:340)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:125)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:413)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validationMessagesInvalidEmailPasswordTest -->
        <test-method is-config="true" signature="afterMethod()[pri:0, instance:test.LoginTest3@1fa121e2]" started-at="2018-11-12T19:42:06Z" name="afterMethod" finished-at="2018-11-12T19:42:09Z" duration-ms="2793" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method is-config="true" signature="beforeMethod()[pri:0, instance:test.LoginTest3@1fa121e2]" started-at="2018-11-12T19:42:09Z" name="beforeMethod" finished-at="2018-11-12T19:42:19Z" duration-ms="10410" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method signature="validationMessagesInvalidEmailPasswordTest(java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:test.LoginTest3@1fa121e2]" started-at="2018-11-12T19:42:19Z" name="validationMessagesInvalidEmailPasswordTest" data-provider="negativeValidDataProviderLoginSubmitPage" finished-at="2018-11-12T19:42:20Z" duration-ms="25" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[test199514@gmail.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[asdwqasdfeasdwqasdfeasdwqasdfeasdwqasdfeasdwqasdfeasdwqasdfeasdwqasdfeasdwqasdfeasdwqasdfeasdwqasdfeasdwqasdfeasdwqasdfeasdwqasdfeasdwqasdfe]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[РЈРєР°Р¶РёС‚Рµ РґРµР№СЃС‚РІРёС‚РµР»СЊРЅС‹Р№ Р°РґСЂРµСЃ СЌР». РїРѕС‡С‚С‹.]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[Р­С‚Рѕ РЅРµРІРµСЂРЅС‹Р№ РїР°СЂРѕР»СЊ. РџРѕРІС‚РѕСЂРёС‚Рµ РїРѕРїС‹С‚РєСѓ РёР»Рё РёР·РјРµРЅРёС‚Рµ РїР°СЂРѕР»СЊ.]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Login page is not loaded. expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Login page is not loaded. expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at test.LoginTest3.validationMessagesInvalidEmailPasswordTest(LoginTest3.java:72)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:379)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:340)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:125)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:413)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validationMessagesInvalidEmailPasswordTest -->
        <test-method is-config="true" signature="afterMethod()[pri:0, instance:test.LoginTest3@1fa121e2]" started-at="2018-11-12T19:42:20Z" name="afterMethod" finished-at="2018-11-12T19:42:23Z" duration-ms="3302" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method is-config="true" signature="beforeMethod()[pri:0, instance:test.LoginTest3@1fa121e2]" started-at="2018-11-12T19:42:23Z" name="beforeMethod" finished-at="2018-11-12T19:42:35Z" duration-ms="11681" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method signature="validationMessagesInvalidEmailPasswordTest(java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:test.LoginTest3@1fa121e2]" started-at="2018-11-12T19:42:35Z" name="validationMessagesInvalidEmailPasswordTest" data-provider="negativeValidDataProviderLoginSubmitPage" finished-at="2018-11-12T19:42:35Z" duration-ms="21" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[test199514@gmail.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[ghtyhgvbnhghtyhgvbnhghtyhgvbnhghtyhgvbnhghtyhgvbnhghtyhgvbnhghtyhgvbnhghtyhgvbnhghtyhgvbnhghtyhgvbnhghtyhgvb]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[РЈРєР°Р¶РёС‚Рµ РґРµР№СЃС‚РІРёС‚РµР»СЊРЅС‹Р№ Р°РґСЂРµСЃ СЌР». РїРѕС‡С‚С‹.]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[Р­С‚Рѕ РЅРµРІРµСЂРЅС‹Р№ РїР°СЂРѕР»СЊ. РџРѕРІС‚РѕСЂРёС‚Рµ РїРѕРїС‹С‚РєСѓ РёР»Рё РёР·РјРµРЅРёС‚Рµ РїР°СЂРѕР»СЊ.]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Login page is not loaded. expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Login page is not loaded. expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at test.LoginTest3.validationMessagesInvalidEmailPasswordTest(LoginTest3.java:72)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:379)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:340)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:125)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:413)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validationMessagesInvalidEmailPasswordTest -->
        <test-method is-config="true" signature="afterMethod()[pri:0, instance:test.LoginTest3@1fa121e2]" started-at="2018-11-12T19:42:35Z" name="afterMethod" finished-at="2018-11-12T19:42:38Z" duration-ms="3067" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
      </class> <!-- test.LoginTest3 -->
    </test> <!-- negative -->
  </suite> <!-- All login tests -->
</testng-results>
